### ISSUE TITLE
Please support docker root mode

### ISSUE THREAD

**Issue by schlichtanders** [green-coding-solutions/green-metrics-tool#217]
I just wanted to try out green-metrics-tool, however it requires docker root-less mode. I would need to setup another user on my laptop and configure that one, which is impressively complicated. My vision was to try out green-metrics-tool, spend 3 hours, and having something working.

As the documentation does not name a crucial reason why root docker is not supported (yet), I guess it is at least possible to support it.

Having docker root support is of course a kind of XY problem - the final problem is to have an easy way to install green-metrics-tool as a package on your system, so that you can try out green-metrics-tool within 1 hour or something.

**Comment by ArneTR** [comment]
Hey @schlichtanders ,

thanks for the issue! 

Can you detail the problems that you had with enabling docker rootless mode? Did you spot the part in the documentation that had an explanation about it?

Generally if you are on a classic laptop setup your normal login user is already a non-root user (since your are not "root" I guess in your normal terminal), so creating a user is not necessary.

Maybe the documentation is too confusing here and we are super happy you bring the case up. The goal is exactly what you mention: A setup time of less then 10 minutes even is what we target.

The reason why docker rootless is not supported lies in the fact that our reporters have to work differntly when targeting a rootless orchestration than a "rootful" one. Systemd saves data in different places and also forwarding is setup in a different place. Just so you have a reason why we choose to only support one mode.
The benefit we get from Docker rootless mode is an increased security as we run the same code on our servers that we document for a "home / dev" setup.

As said: I would like to get your feedback on my question above and then help you getting it set up.

**Comment by ArneTR** [comment]
Also a follow up question to you: Do you have for instance also podman installed on your system or ever worked with it? We had the discussion internally to circumevent the Docker rootless mode setup by using a different orchestrator that might be easiert for devs to interact with ...

**Comment by ArneTR** [comment]
Hey @schlichtanders 

I just have found this issue in a 2024 housekeeping session. We actually implemented docker root mode a while ago: https://github.com/green-coding-berlin/green-metrics-tool/pull/488

Are you interested in giving the tool another spin? :)

**Comment by ArneTR** [comment]
Since no update came on this Issue we close it. Has been implemented
