### ISSUE TITLE
Constant value for network transmission energy calculation

### ISSUE THREAD

**Issue by davidkopp** [green-coding-solutions/green-metrics-tool#707]
For 2024 the constant value of $0.0028125\ \frac{kWh}{GB}$ is used to calculate the network transmission energy as documented [here](https://www.green-coding.io/co2-formulas/).
Based on my calculation, the number should be $0.00265165\ \frac{kWh}{GB}$. It's only a minor difference and not important at all. Yet there is a difference, and I wonder why.

Used formula:

$\text{Value of year before} \times \sqrt{2}$

Starting year is 2015 with the value of $0.06\ \frac{kWh}{GB}$.

**Comment by ArneTR** [comment]
just for clarity and people coming into this conversation: YOu meant 1/sqrt(2) I guess.

Acutally your way of calculating looks sound. I used a different approach:
```
Year 2023 = 0.06 / 2 / 2 / 2 / 2 = 0.00375
Year 2025 = 0.06 / 2 / 2 / 2 / 2 / 2 = 0.001875

Difference between these two - halfed:  0.001875 / 2 = 0.0009375

Now subtracting this half difference from Year 2023 => 0.00375 - 0.0009375
```

On my first understanding these values should be identical as the abatement is linear proportional. I am most likely not spotting something obvious, but maybe you see the error directly.

**Comment by davidkopp** [comment]
Great. I will close this issue.

**Comment by davidmytton** [comment]
Thanks for tagging me. I'll check the calculations in that post you mentioned. However, you really shouldn't use the average network energy intensity per GB to calculate total energy consumption - it's not accurate and doesn't represent how networks work. It's only valid for understanding the energy intensity when you know the total energy and total data transferred over the network in a given historical period. It has no use for making predictions or calculations about current or future energy consumption.

**Comment by ArneTR** [comment]
Hey @davidmytton - I am quite aware of the downsides. Please give our explanation why we use it here a read: https://www.green-coding.io/co2-formulas/

> However this model is not without critique, as the real nature of network devices to date is that they consume 80% of their peak capacity already in idle mode. The rest is a proportional factor according to the usage of the possible bandwidth. Many models have been proposed to better attribute this reality on the real electricity cost for application that uses the network, however time-share or data-share models all have different downsides [2].

> We deciced to use the linear approach of network transfer attribution to power consumption in our tools as it bests incentives the user to keep the network traffic to a minimum. No matter which current known calculation method is used it will be inaccurate still and none of the current methods can reliably incorporate the real costs of provisioning new hardware for bandwith increase back in time to the pool of applications that tipped the providers to increase the bandwith.

The idea here is really to create something like an actionable, not an accurate metric. What do you think on that?

**Comment by davidmytton** [comment]
I just checked where I got the 0.0065 kWh/GB 2020 figure from and it's based on a regression analysis of the [Aslan paper](https://doi.org/10.1111/jiec.12630) in the [Carbon Impact of Video Streaming report](https://www.carbontrust.com/our-work-and-impact/guides-reports-and-tools/carbon-impact-of-video-streaming) by the Carbon Trust, so I do believe it's accurate.

> I am quite aware of the downsides. Please give our explanation why we use it here a read: https://www.green-coding.io/co2-formulas/ ... The idea here is really to create something like an actionable, not an accurate metric. What do you think on that?

Thanks. I read that and I agree using the average intensity might make users take action, but on a false belief that reducing their data transfer will impact the energy consumption of networks. There's almost no relationship between data transfer volume and network energy consumption so I don't think we should be presenting metrics as if there were.  

Data volumes have been growing significantly yet overall network energy consumption has plateued. It's the wrong place to focus and makes users think they can have an impact by making irrelevant changes. Better to focus on where the majority of the impact is, such as with user devices.

**Comment by ArneTR** [comment]
Hey @davidmytton,

although this issue is closed I thought it might be an interesting spot to continue a discussion on the cost of networking.

I noticed your recent paper ([Network energy use not directly proportional to data volume: The power model approach for more reliable network energy consumption calculations](https://onlinelibrary.wiley.com/doi/10.1111/jiec.13512)) which now gives a more concise approach to attribute network cost and better highlight that data transfer is not so much of an issue compared to the fixed costs.

My question: In case you would like to use the model to create a profile of a software application, how do you rate  the time when a software is not actually sending data?

Concrete example: Assuming a software is doing a 12 hour calculation job and sending the results over the wire. In your case a software would be rated identically no matter if data is sent in chunks every 10 seconds or in one super big blob at the end (assuming same bandwidth usage for both cases).

So when does a software officially count as "not using the network" and thus the carbon costs would not be attributed to the software? (Thinking here in similar mindsets as the GHG protocol / Scope 3 works).

Since plain network connectivity is uqbiquitous in your model the fixed cost of the networks would accrue constantly if I understand it correctly? 

I assume you know the time attribution model in the SCI from the Green Software Foundation? Here for instance the embodied carbon cost only are attributed to the software for the time it is actually using it. When the hardware is given back to the cloud provider for instance and "idling" it will be attributed to their books and not the cloud client anymore.

Very interested to hear your take on this.

**Comment by davidmytton** [comment]
Thanks for taking a look at the paper! 

> My question: In case you would like to use the model to create a profile of a software application, how do you rate the time when a software is not actually sending data?

If you're using an attribution model, then the software would not be allocated any network energy if it's not sending any data. If it's not allocated to the software then it has to be allocated somewhere else (the cloud provider in your example).

The assumption is that you already have the total energy and total transfer over the network i.e. you're making a historical calculation to allocate energy for reporting purposes.

If you're trying to calculate the present or future usage then that's where the power model from the paper comes in. You'd have to break down the relevant network components to understand the baseline power and what the marginal increase is whilst the software is using the network.

That's my initial thought - is that what you'd expect?

**Comment by alexzurbonsen** [comment]
Hey, I hope it's fine to pick up this conversation again. I am trying to understand pros and cons of the different approaches.

To me, the main difference between the kWh/GB and power model approach, seems to be that the latter, the power model, includes usage time, because it models power instead of energy consumption. When calculating energy consumption from the power model, it makes a difference if you send 1MB over the wire in 1 second or in 1 minute. Whereas it doesn't make a difference with the kWh/GB approach. Is that correct?

@davidmytton I am not sure why the power model should enable calculating present or future usage in a better way than the kWh/GB model? The power model is essentially `P = P_idle + P(data)` for each network component. But it seems to me that the `P_idle` offsets are also historical averages, i.e. power usage per subscriber. In terms of predictive power there isn't any difference to the kWh/GB approach or did I miss anything?

To me, the main difference between both models thus seems to be in the way consumption is attributed to users. Whereas the kWh/GB model attributes all energy consumption to users, the power model might not. This is intransparent to me though. It seems to depend on how the `P_idle`s are actually calculated. Let's say they are calculated for one device as `P_idle = E_total / t_total / N_total` (where `E_total` is the energy used by the device in timespan `t_total`, `N_total` is number of subscribers served in the time `t_total`, and `t_total` is in seconds) you would attribute the consumption for the time `t_total - t_average_usage_time_of_subscribers` to the network provider assuming the number of subscribers stays constant. But that is not given if you are calculating current or future consumption.

According to the attribution time model that @ArneTR mentioned, this might be fair. But it is pretty intransparent which portion of the consumption is attributed to users and which to the provider if you are using the power model with historical `P_idle`s as an attribution model.

Being actionable: It seems that both approaches do not model the dependency of the overall network's energy consumption on user behaviour. This is because the idle power draw dominates a network's energy consumption. But in the power model it is a constant, i.e. it does not depend on any user behaviour. In the kWh/GB model it is not included. 

Naively, one might have to think of a metric that penalizes data consumption at peak load times, based on the, I guess naive, assumption that the network is provisioned for peak loads.

**Comment by ArneTR** [comment]
The network traffic share attribution model does not model any idle behaviour, that is correct.
Depending on which "accounting framework" you image as the underlying methodology though it also should not necessarily do so.

When for instance using cloud resources the "idle cost" of the systems, if you are not currently using them, are not attributed to you.

For a network this is very debateable when and how you count as "connected". Is it having the computer turned on? Or is it having just a contact with an ISP even if no device plugged in? Or only if I am sending keep alive packets?

I think both models have different approaches and if you are targeting software developers the plain sending of data might be a better metric to communicate CO2 with. for end users maybe the used time on the network is better.

Since both values incorporate anyway highly uncertain values, and there are even more specualitve models out there like the SWD model, I think it makes most sense to only use them to benchmark against one self OR against fixed setups in similar environments / benchmarks.

my 2 cents :)
